spring.application.name=library-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/altis_library
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

logging.level.org.flywaydb=DEBUG

admin.email=${ADMIN_EMAIL}
admin.password=${ADMIN_PASSWORD}
admin.name=${ADMIN_NAME}
admin.phone=${ADMIN_PHONE}
admin.cpf=${ADMIN_CPF}
admin.birth-date=${ADMIN_BIRTH_DATE}
admin.address=${ADMIN_ADDRESS}